spring:
  profiles:
    active: "local"
    group:
      "local": "localDB, devPort, web-mvc"
      "dev": "devDB, devPort, web-mvc"
      "prod": "prodDB, prodPort, web-mvc"
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 150MB

images:
  path: ${UPLOADED_IMAGE_PATH}

webclient:
  url: ${WEBCLIENT_BASE_URL}

---

spring:
  config:
    activate:
      on-profile: "localDB"

  datasource:
    url: ${DATASOURCE_URL_LOCAL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: select 1
  sql:
    init:
      platform: mysql

---

spring:
  config:
    activate:
      on-profile: "devDB"

  datasource:
    url: ${DATASOURCE_URL_DEV}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: select 1
  sql:
    init:
      platform: mysql

---

spring:
  config:
    activate:
      on-profile: "prodDB"

  datasource:
    url: ${DATASOURCE_URL_PROD}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: select 1
  sql:
    init:
      platform: mysql

---

spring:
  config:
    activate:
      on-profile: "devPort"

server:
  port: 9000

---

spring:
  config:
    activate:
      on-profile: "prodPort"

server:
  port: 9001

---

spring:
  config:
    activate:
      on-profile: "web-mvc"

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  messages:
    basename: errors
